name: "Block Merge and Autosquash Commits"
description: "Prevent merging pull requests that contain merge commits and commits with messages prefixed with fixup! or squash!"
author: "nineinchnick"
branding:
  icon: "alert-circle"
  color: "Red"

inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
    default: ${{ github.token }}
  check-merge:
    description: 'Check for and block merge commits.'
    default: true
  check-fixup:
    description: 'Check for and block fixup commits.'
    default: true

runs:
  using: "docker"
  image: "Dockerfile"
