name: Block on fixup and merge commits

on: pull_request

permissions:
  pull-requests: read

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3

      - uses: ./
